version: "3.7"

services:
  finxi-challenge:
    container_name: finxi-challenge
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"

    ports:
      - "8081:8080"
